apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "container-image-exporter-node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container-image-exporter-node.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "container-image-exporter-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "container-image-exporter-node.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "container-image-exporter-node.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: node-exporter
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ required "image.repository is required" .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - node-exporter
            - --metrics-bind-address=:{{ .Values.metricsPort }}
            - --cri-socket={{ .Values.criSocket }}
            - --proc-root={{ .Values.procRoot }}
            - --only-images-in-use={{ .Values.onlyImagesInUse }}
            {{- range .Values.labelAllowlist }}
            - --label-allowlist={{ . }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metricsPort }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: proc
              mountPath: {{ .Values.procRoot }}
              readOnly: true
            - name: cri-sock
              mountPath: {{ .Values.criSocket | dir }}
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: cri-sock
          hostPath:
            path: {{ .Values.criSocket | dir }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
