{{- if and .Values.clusterExporter.enabled .Values.clusterExporter.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "container-image-exporter.clusterExporter.fullname" . }}
  labels:
    {{- include "container-image-exporter.clusterExporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "container-image-exporter.clusterExporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "container-image-exporter.clusterExporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
