{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "container-image-exporter-cluster.fullname" . }}
  labels:
    {{- include "container-image-exporter-cluster.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
{{- if .Values.k8sKeychain }}
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts"]
  verbs: ["get", "list"]
{{- end }}
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
{{- with .Values.rbac.extraRules }}
{{- toYaml . | nindent 0 }}
{{- end }}
{{- end }}
