apiVersion: v1
kind: Service
metadata:
  name: {{ include "container-image-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container-image-exporter.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ range .Values.service.ports }}{{ if eq .name "metrics" }}{{ .port | quote }}{{ end }}{{ end }}
    prometheus.io/path: "/metrics"
spec:
  selector:
    {{- include "container-image-exporter.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
  {{- end }}