{
 "title": "Chainguard Adoption - Node Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_image_container_os_info,exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OS Distribution",
   "type": "piechart",
   "description": "The OS distribution of running containers sourced from /etc/os-release, as reported by the node exporter. Containers with no /etc/os-release (e.g. scratch images) are excluded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (id) (\n  container_image_container_os_info{exported_namespace=~\"$namespace\", id!=\"\"}\n)\n",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Chainguard vs Non-Chainguard",
   "type": "piechart",
   "description": "The percentage of running containers whose /etc/os-release identifies the OS as Chainguard versus any other OS.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (value) (\n    label_replace(\n      container_image_container_os_info{exported_namespace=~\"$namespace\", id=~\"chainguard|wolfi\"},\n      \"value\", \"Chainguard / Wolfi\", \"\", \"\"\n    )\n  or\n    label_replace(\n      container_image_container_os_info{exported_namespace=~\"$namespace\", id!~\"chainguard|wolfi\"},\n      \"value\", \"Non-Chainguard\", \"\", \"\"\n    )\n)\n",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Non-Chainguard Containers",
   "type": "table",
   "description": "Containers that are not running Chainguard images or images based on Chainguard images.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max(container_image_container_os_info{exported_namespace=~\"$namespace\",id!~\"wolfi|chainguard\"}) by (exported_namespace,exported_pod,exported_container,image)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Distribution Over Time",
   "type": "timeseries",
   "description": "The count of running containers by OS id over time.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count by (id) (container_image_container_os_info{exported_namespace=~\"$namespace\"})\n",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Chainguard / Wolfi % Over Time (by Namespace_",
   "type": "timeseries",
   "description": "The percentage of running containers identified as Chainguard  by /etc/os-release over time.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * count(\n  container_image_container_os_info{exported_namespace=~\"$namespace\", id=~\"chainguard|wolfi\"}\n) by (exported_namespace)\n/ count(\n  container_image_container_os_info{exported_namespace=~\"$namespace\"}\n) by (exported_namespace)\n",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  }
 ]
}