{{- if .Values.nodeExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "container-image-exporter.nodeExporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container-image-exporter.nodeExporter.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ range .Values.nodeExporter.service.ports }}{{ if eq .name "metrics" }}{{ .port | quote }}{{ end }}{{ end }}
    prometheus.io/path: "/metrics"
    {{- with .Values.nodeExporter.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "container-image-exporter.nodeExporter.selectorLabels" . | nindent 4 }}
  clusterIP: {{ .Values.nodeExporter.service.clusterIP }}
  ports:
  {{- range .Values.nodeExporter.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
  {{- end }}
{{- end }}
