{{- if .Values.nodeExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "container-image-exporter.nodeExporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container-image-exporter.nodeExporter.labels" . | nindent 4 }}
  {{- if or .Values.nodeExporter.service.scrapeAnnotations .Values.nodeExporter.service.annotations }}
  annotations:
    {{- if .Values.nodeExporter.service.scrapeAnnotations }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.nodeExporter.metricsPort | quote }}
    prometheus.io/path: "/metrics"
    {{- end }}
    {{- with .Values.nodeExporter.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  selector:
    {{- include "container-image-exporter.nodeExporter.selectorLabels" . | nindent 4 }}
  clusterIP: {{ .Values.nodeExporter.service.clusterIP }}
  ports:
    - name: metrics
      port: {{ .Values.nodeExporter.metricsPort }}
      targetPort: metrics
      protocol: TCP
{{- end }}
