{{- if and .Values.nodeExporter.enabled .Values.nodeExporter.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "container-image-exporter.nodeExporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container-image-exporter.labels" . | nindent 4 }}
  {{- with .Values.nodeExporter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.nodeExporter.serviceAccount.automount }}
{{- end }}
