{{- if and .Values.nodeExporter.enabled .Values.nodeExporter.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "container-image-exporter.nodeExporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container-image-exporter.nodeExporter.labels" . | nindent 4 }}
    {{- with .Values.nodeExporter.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "container-image-exporter.nodeExporter.selectorLabels" . | nindent 6 }}
{{- end }}
